version: '2'
services:
  dashboard:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/home/user/dashboard

  dashboard-test:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: nosetests -v -s
    volumes:
      - .:/home/user/dashboard
