version: '2'
services:
  dashboard:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    volumes:
      - ..:/dashboard
    ports:
      - 8080

  build-docs:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    entrypoint: bash -c 'cd docs && make html'
    volumes:
      - ..:/dashboard

  dashboard-test:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    entrypoint: nosetests -v -s --with-coverage --cover-xml-file=/dashboard/coverage.xml --cover-xml 
    volumes:
      - ..:/dashboard
