version: '2'
services:
  dashboard:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    volumes:
      - ..:/home/user/dashboard
    ports:
      - 8080

  build-docs:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    entrypoint: bash -c 'cd docs && make html'
    volumes:
      - ..:/home/user/dashboard

  dashboard-test:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    entrypoint: nosetests -v -s
    volumes:
      - ..:/home/user/dashboard
